[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "sonars",
]

[profile.dev.package."*"]
opt-level = 3

# (hopefully) the best of both worlds from debug and release
[profile.mid]
inherits = "dev"
debug = 1
opt-level = 3
incremental = true

