[package]
name = "sonars"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
# bevy_winit render bevy_asset bevy_gilrs bevy_scene wayland x11
bevy = {version = "0.9", default-features = false, features = ["bevy_winit","render", "x11"]}
bevy_egui = "0.19.0"
once_cell = "1.17.0"
thiserror = "1.0.38"
wasm-bindgen = "0.2.84"
web-sys = {version = "0.3.61", features=[  
    'AudioContext',
    'AudioDestinationNode',
    'AudioNode',
    'AudioParam',
    'GainNode',
    'AudioBuffer',
    'AudioBufferOptions',
    'AudioBufferSourceNode']}


[features]
dev = ["bevy/dynamic"]

