[package]
name = "sonars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_egui = "0.14.0"
once_cell = "1.17.0"
rodio = {version = "0.16.0", default-features = false}


[features]
dev = ["bevy/dynamic"]

